# Generated by Django 2.1.5 on 2019-02-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190207_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='summary',
            new_name='YT_Link',
        ),
    ]
